var Chinese = {
  loading: "加载中···",
  loginTitle: "登录",
  button: "中文",
  account: "账号",
  password: "密码",
  fpwd: "忘记密码",
  accountp: "输入账号",
  passwordp: "输入密码",
  loginError: "请输入正确的账号或密码",
  //注册
  fp_tips: "密码将发到您的邮箱",
  email: "邮箱",
  email_inpt: "邮箱地址",
  register: "注册",
  already_Member: "已有账号",
  login: "登录",
  submit: "确定",
  save: "保存",
  edit_s: "编辑",
  //创建账号
  create_account: "创建账号",
  fullname: "全名",
  fullname_tips: "输入全名",
  first_name: "名字",
  first_name_tips: "输入您的名字",
  last_name: "姓氏",
  last_name_tips: "输入您的姓氏",
  username_err: "账号不可用",
  username_ck: "用户名只能包含字母、数字和@.+-_",
  password_err: "密码不可用",
  email_err: "邮箱不可用",
  firstname_err: "名字不可用",
  lastname_err: "姓氏不可用",

  //首页
  my_rofile: "个人资料",
  my_address: "我的地址",
  my_order: "订单",
  my_cart: "购物车",
  other: "其他",
  need_help: "帮助",
  share: "分享好友",
  about_us: "关于我们",
  logout: "退出",
  meat: "肉",
  dairy: "奶制品",
  dry_goods: "干货",
  seafood: "海鲜",
  new_arrivals: "新品推荐",
  shop_now: "去看看",
  great: "爆",
  deals: "品",
  left_in_stop: "剩余",
  add: "添加",
  box: "盒",
  meet_our: "即将",
  newarrivals: "推出",
  choose_location: "选择收货地址",
  location_des: "您的位置方便向您展示商品的可用性和价格",
  enter_zip: "输入邮编",
  price_des: "价格可能因地点而异",
  continuew: "继续",
  //个人信息
  available_balance: "可用余额",
  payment_cards: "支付卡",
  address: "地址",
  phone: "电话",
  payment_tips: "管理支付卡",
  address_tips: "管理地址",
  recent: "最近",
  search: "搜索",
  similar: "类似",
  products: "产品",
  //detail
  add_to_cart: "加入购物车",
  add_and_checkout: "加入并结算",
  //orderhistory
  order_no: "订单号",
  order_success: "订单成功",
  repeat: "再次购买",
  //orderfilter
  searchby: "搜索",
  search_from_last: "近期搜索",
  searchby_date: "日期搜索",
  searchby_tips: "姓名, 订单号.....",
  pfrom: "开始",
  pto: "结束",
  month: "月",
  //filter
  reset: "重置",
  apply: "继续",
  //produce
  total: "共",
  //addaddress
  address_name: "地址名称",
  add_address: "添加地址",
  zip_code: "邮政编码",
  city: "城市",
  address_tips: "省/市/区",
  address_line1: "地址行1",
  address_line2: "地址行2",
  address_example: "北京",
  street: "街道",
  is_defalut: "是否默认",
  city_err:"城市不能为空",
  state_err:"地区不能为空",
  street_err:"街道不能为空",
  zipcode_err:"邮编不能为空",
  //add new card
  name_card: "卡主姓名",
  card_type: "卡片类型",
  card_num: "卡号",
  expiry_date: "有效期",
  save_checkbox: "安全保存您的卡详细信息",
  add_card: "添加卡片",
  //selectaddress
  proceed_payment: "继续支付",
  add_new_address: "添加新地址",
  //savecard
  add_new_card: "添加新卡",
  //payment options
  amount_payable: "应付金额",
  save_card: "储蓄卡",
  credit_card: "信用卡",
  debit_card: "借记卡",
  net_banking: "网上银行",
  pay_on_delivery: "货到付款",
  taxes: "含税",
  //my cart2
  checkout: "结算",
  sub_total: "小计",
  grand_total: "总计",
  coupon_tips:"输入可用优惠码",
  apply_code: "优惠码",
  change:"修改",
  no_tip:"无",
  //my cart
  personal_detail: "个人资料",
  delivery_address: "送货地址",
  place_order: "下单",
  cvv: "下一步输入信用卡cvv代码",
  cvv: "ENTER CVV ON NEXT STEP",
  //checkout
  track_order: "跟踪订单",
  check_word1: "恭喜！您的的订单已被接收！",
  chekc_word2: "您的物品正在路上，应该很快就到。",
  credit_card: "信用卡号",
  card_tips:"请检查您的卡号",
  yes: "确定",
  cancel: "取消",
  credit_reference: "卡片参考号",
  card_reference_tips: "请检查卡片参考号",
  pay_type_tips: "请选择支付方式",
  weichar_pay: "微信支付",
  credit_card: "信用卡",
  pay_type: '支付方式',
  exp_month: "有效期月",
  exp_year: "有效期年",
  select_add:'请添加收货地址',
  add_cart_success:"已加入购物车",
}

module.exports = {
  content: Chinese
}