var English = {
  loading: "Loading···",
  loginTitle: "Login",
  button: "English",
  account: "USER NAME",
  password: "PASSWORD",
  fpwd: "Forgot Password",
  accountp: "Enter your username",
  passwordp: "Enter your password",
  loginError: "Incorrect username or password",
  //forgot password
  fp_tips: "We will send an password on your registered email id",
  email: "EMAIL",
  email_inpt: "Enter your email",
  register: "Register",
  already_Member: "Already Member",
  login: "Login",
  submit: "Submit",
  save: "SAVE",
  edit_s: "edit",
  //create account
  create_account: "Create Account",
  fullname: "FULL NAME",
  fullname_tips: "Enter your fullname",
  first_name: "FIRST NAME",
  first_name_tips: "Enter your first name",
  last_name: "LAST NAME",
  last_name_tips: "Enter your last name",
  username_err: "Account unavailable",
  username_ck: "Enter a valid username. This value may contain only letters, numbers and @.+-_ characters.",
  password_err: "Password unavailable",
  email_err: "Email unavailable",
  firstname_err: "FirstName unavailable",
  lastname_err: "LastName unavailable",
  //HOME
  my_rofile: "My Profile",
  my_address: "My Address",
  my_order: "My Order",
  my_cart: "My Cart",
  other: "Other",
  need_help: "Need Help",
  share: "Share",
  about_us: "About us",
  logout: "Logout",
  meat: "Meat",
  dairy: "Dairy",
  dry_goods: "Dry Goods",
  seafood: "SeaFood",
  new_arrivals: "New Arrivals",
  shop_now: "Shop Now",
  great: "Great",
  deals: "deals",
  left_in_stop: "Left in Shop",
  add: "Add",
  box: "Box",
  meet_our: "Meet Our",
  newarrivals: "New Arrivals",
  choose_location: "Choose your location",
  location_des: "Your location lets us show you item availability and prices.",
  enter_zip: "Enter ZipCode",
  price_des: "Prices may vary depending on location.",
  continuew: "Prices may vary depending on location.",
  //profile
  available_balance: "Available Balance",
  payment_cards: "Payment Cards",
  address: "Address",
  phone: "Phone Number",
  payment_tips: "Add view credit or debit card",
  address_tips: "Add or remove view delivery address",
  //Search
  recent: "Recent",
  search: "Search",
  similar: "Similar",
  products: "Products",
  //detail
  add_to_cart: "Add to Cart",
  add_and_checkout: "Add and Checkout",
  //orderhistory
  order_no: "Order No",
  order_success: "Your order is successfully",
  repeat: "Repeat",
  //orderfilter
  searchby: "Search by",
  search_from_last: "Search from last",
  searchby_date: "Search by Date",
  searchby_tips: "Name, Order Number.....",
  pfrom: "From",
  pto: "To",
  month: "Month",
  //filter
  reset: "Reset",
  apply: "Apply",
  //produce
  total: "Total",
  //addaddress
  address_name: "Address Remark",
  add_address: "Add New Address",
  zip_code: "Zip Code",
  city: "City",
  address_tips: "State / Provision / Region",
  address_line1: "Address Line No 1",
  address_line2: "Address Line No 2",
  address_example: "Delhi",
  street: "Street",
  is_defalut: "Dealut",
  city_err: "City no be blank",
  state_err: "State no be blank",
  street_err: "Street no be blank",
  zipcode_err: "Zip code no be blank",
  //add new card
  name_card: "Name on card",
  card_type: "Card Type",
  card_num: "Card number",
  expiry_date: "Expiry date",
  save_checkbox: "Save your card details securely",
  add_card: "Add card",
  //selectaddress
  proceed_payment: "Proceed to payment",
  add_new_address: "Add New Address",
  //savecard
  add_new_card: "Add New Card",
  //payment options
  amount_payable: "Amount Payable",
  save_card: "Saved Card",
  credit_cardo: "Card",
  debit_card: "Debit Card",
  net_banking: "Net Banking",
  pay_on_delivery: "Pay on Delivery",
  taxes: "Incl. of all taxes",
  //my cart2
  checkout: "Checkout",
  sub_total: "Sub total",
  grand_total: "Grand Total",
  coupon_tips: "Enter your coupon code if you have",
  apply_code: "Apply code",
  change: "CHANGE",
  no_tip: "No Tip",
  //my cart
  personal_detail: "Personal Detail",
  delivery_address: "Delivery address to",
  place_order: "Place order",
  cvv: "ENTER CVV ON NEXT STEP",
  //checkout
  track_order: "Track your order",
  check_word1: "Congratulations. Your order is accpeted !",
  chekc_word2: "Your items are on the way and should arrive shortly.",
  credit_card: "Card Number",
  card_tips: "Please check the card number.",
  yes: "Yes",
  cancel: "Cancel",
  credit_reference: "Card Reference Number",
  card_reference_tips: "Please check the Reference number.",
  pay_type_tips: "Please choose the mode of payment",
  weichar_pay: "WeChat",
  credit_cardp: "Card",
  pay_type: 'Payment',
  exp_month: "expiry month",
  exp_year: "expiry year",
  select_add: 'Please add the receiving address',
  add_cart_success: "Success",
  product_name:"Product Name",
}

module.exports = {
  content: English
}